name: Build

on:
  push:
  pull_request:

jobs:
  windows:
    name: Windows CMake
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release --prefix dist

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: prac-task3-windows-x64
          path: dist
